### ISSUE TITLE
discordrb should make rbnacl gem optional

### ISSUE THREAD

**Issue by pocari** [discordrb/discordrb#639]
# Summary

When using the discrodrb gem and the jwt gem at the same time, it seems that #621 events occur.

The reason is that the dependency on discordb contains the rbnacl gem.

The discordrb gem does not use rbnacl in some cases, so it is not essential for dependencies.(https://github.com/meew0/discordrb/blob/master/lib/discordrb/voice/network.rb#L10-L21)

On the other hand, the jwt gem is used with the rbnacl gem but is not a required dependency. The jwt gem generates an error only when rbnacl is present in the load path.

For this reason, the jbt gem does not expect that libsodium.so does not exist even though rbnacl is in the load path. (https://github.com/jwt/ruby-jwt/blob/master/lib/jwt/signature.rb#L14)

The behavior of the jwt gem feels more natural to me, so it would be better to do this for the discordb gem as well.
And I think that it is better to stop the control of rbnacl require by the environment variable.

This is the minimum case to reproduce the error.
---

```
% cat Gemfile
# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "discordrb"
gem "jwt"
% DISCORDRB_NONACL=1 bundle exec ruby -e "require 'discordrb'; require 'jwt'"
Traceback (most recent call last):
        18: from -e:1:in `<main>'
        17: from -e:1:in `require'
        16: from /Users/pocari/dev/tmp/20190627/jwt-discordrb/vendor/bundle/ruby/2.6.0/gems/jwt-2.2.1/lib/jwt.rb:5:in `<top (required)>'
        15: from /Users/pocari/dev/tmp/20190627/jwt-discordrb/vendor/bundle/ruby/2.6.0/gems/jwt-2.2.1/lib/jwt.rb:5:in `require'
        14: from /Users/pocari/dev/tmp/20190627/jwt-discordrb/vendor/bundle/ruby/2.6.0/gems/jwt-2.2.1/lib/jwt/decode.rb:5:in `<top (required)>'
        13: from /Users/pocari/dev/tmp/20190627/jwt-discordrb/vendor/bundle/ruby/2.6.0/gems/jwt-2.2.1/lib/jwt/decode.rb:5:in `require'
        12: from /Users/pocari/dev/tmp/20190627/jwt-discordrb/vendor/bundle/ruby/2.6.0/gems/jwt-2.2.1/lib/jwt/signature.rb:12:in `<top (required)>'
        11: from /Users/pocari/dev/tmp/20190627/jwt-discordrb/vendor/bundle/ruby/2.6.0/gems/jwt-2.2.1/lib/jwt/signature.rb:12:in `require'
        10: from /Users/pocari/dev/tmp/20190627/jwt-discordrb/vendor/bundle/ruby/2.6.0/gems/rbnacl-3.4.0/lib/rbnacl.rb:4:in `<top (required)>'
         9: from /Users/pocari/dev/tmp/20190627/jwt-discordrb/vendor/bundle/ruby/2.6.0/gems/rbnacl-3.4.0/lib/rbnacl.rb:4:in `require'
         8: from /Users/pocari/dev/tmp/20190627/jwt-discordrb/vendor/bundle/ruby/2.6.0/gems/rbnacl-3.4.0/lib/rbnacl/sodium/version.rb:3:in `<top (required)>'
         7: from /Users/pocari/dev/tmp/20190627/jwt-discordrb/vendor/bundle/ruby/2.6.0/gems/rbnacl-3.4.0/lib/rbnacl/sodium/version.rb:4:in `<module:RbNaCl>'
         6: from /Users/pocari/dev/tmp/20190627/jwt-discordrb/vendor/bundle/ruby/2.6.0/gems/rbnacl-3.4.0/lib/rbnacl/sodium/version.rb:6:in `<module:Sodium>'
         5: from /Users/pocari/dev/tmp/20190627/jwt-discordrb/vendor/bundle/ruby/2.6.0/gems/rbnacl-3.4.0/lib/rbnacl/sodium/version.rb:9:in `<module:Version>'
         4: from /Users/pocari/dev/tmp/20190627/jwt-discordrb/vendor/bundle/ruby/2.6.0/gems/rbnacl-3.4.0/lib/rbnacl/sodium/version.rb:9:in `extend'
         3: from /Users/pocari/dev/tmp/20190627/jwt-discordrb/vendor/bundle/ruby/2.6.0/gems/rbnacl-3.4.0/lib/rbnacl/sodium.rb:12:in `extended'
         2: from /Users/pocari/dev/tmp/20190627/jwt-discordrb/vendor/bundle/ruby/2.6.0/gems/ffi-1.11.1/lib/ffi/library.rb:99:in `ffi_lib'
         1: from /Users/pocari/dev/tmp/20190627/jwt-discordrb/vendor/bundle/ruby/2.6.0/gems/ffi-1.11.1/lib/ffi/library.rb:99:in `map'
/Users/pocari/dev/tmp/20190627/jwt-discordrb/vendor/bundle/ruby/2.6.0/gems/ffi-1.11.1/lib/ffi/library.rb:145:in `block in ffi_lib': Could not open library 'sodium': dlopen(sodium, 5): image not found. (LoadError)
Could not open library 'libsodium.dylib': dlopen(libsodium.dylib, 5): image not found
```

## Environment
any anvironment

**Ruby version:**

```
% ruby -v
ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-darwin18]
```

I'm working around with the following changes:
https://github.com/pocari/discordrb/commit/4953b3146df5ada8a5215c194dba6a75080eb2c0

```
% cat Gemfile
# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'discordrb', git: 'https://github.com/pocari/discordrb', branch: 'fix-rbnacl-dependency'
gem "jwt"
% bundle exec ruby -e "require 'discordrb'; require 'jwt'"
% echo $?
0
% bundle exec ruby -e "require 'rbnacl'"
Traceback (most recent call last):
        1: from -e:1:in `<main>'
-e:1:in `require': cannot load such file -- rbnacl (LoadError)
```

**Comment by merefield** [comment]
This makes sense.  I was aiming to use this gem for a Discourse plugin, but there's no way to ensure lib sodium.so is installed on the target - the plugin architecture will only take care of gem dependencies, not any additional object libraries.  The host in that case is a third party docker container you don't have control of as the plugin developer.  A way of incorporating this without needing to depend on libsodium would be very useful, especially given the voice functionality is not a requirement for many.  Forgive me if I'm missing something.

**Comment by z64** [comment]
Hi @pocari, thanks for opening an issue. However it isn't clear to us how this issue is related to discordrb.

The  uncaught `LoadError` that has leaked to the top level is raised from `jwt` as intended, on their part, as far as I can see. When you `require` something in ruby, it will not clean up after itself - if some constants managed to get defined as the library was being interpreted, they will remain in scope even after the require "fails".

```
➜  cat foo.rb 
module Foo
end

raise "woops!"
➜  pry
[1] pry(main)> require "./foo"
RuntimeError: woops!
from /home/lune/discordrb-test/foo.rb:4:in `<top (required)>'
[2] pry(main)> Foo
=> Foo
```
The following line from `jwt`:
```rb
rescue LoadError
  raise if defined?(RbNaCl)
```
implicitly re-raises the caught exception:
```
[3] pry(main)> class MyError < Exception
[3] pry(main)* end
=> nil
[4] pry(main)> begin
[4] pry(main)*   raise MyError
[4] pry(main)* rescue MyError
[4] pry(main)*   raise
[4] pry(main)* end
MyError: MyError
```
This means that `jwt` will always raise an uncaught `LoadError` if libsodium is not available.

discordrb's loading mechanism *does not* propagate the `LoadError`. It will *never* raise an uncaught exception trying to find libsodium.

What I've done here is create two isolated docker containers that *do not* have libsodium installed. One container only has rbnacl installed, the other has only discordrb installed.

https://gist.github.com/z64/80db05f07ab19f397eb2692d06e141a3

As intented, if libsodium is not available, discordrb does *not* fail - it is already optional. `jwt` also raises the same error you as seeing, as expected.

If you read my comments in the issue you linked, I show how the exception stems from rails loading mechanisms requiring `jwt` - the backtraces all come from processing `jwt`.

https://github.com/meew0/discordrb/issues/621#issuecomment-494097596

Could you clarify exactly what discordrb should do here? All code and logging shown points to this as an "issue" with `jwt`. The uncaught exception also seems reasonable, as `jwt` *must* be encrypted, and I'm assuming `rbnacl` doesn't provide a fallback encryption method.

**Comment by swarley** [comment]
Do you plan on submitting your changes as a PR?

**Comment by pocari** [comment]
I did not understand my proposal correctly, so I wanted to ask for an opinion.

If agreement is obtained, I think that I will propose https://github.com/pocari/discordrb/commit/4953b3146df5ada8a5215c194dba6a75080eb2c0 as PR.

**Comment by z64** [comment]
Hi @pocari, 

I have opened #641 to remove our dependency on the gem entirely. Your review and testing are welcome.

This way, "everyone wins":
- `rbnacl` is gone from our dep tree, so no conflicts
- No conflicts are possible
- One less dependency in our gemspec
- Requires no changes for existing voice users (they don't have to all add `rbnacl` to their gemfiles, etc)

Theoretically, the "same" problem would exist with another gem that "optionally" requires opus in a similar manner. In favor of keeping things simple for our users / not forcing them to change their environments, I'll leave it alone unless a similar issue comes up with it as well. Plus, In-house opus bindings wouldn't be as simple.

**Comment by pocari** [comment]
Hi @z64,

I have checked #641 .  The problem no longer occurs, Thanks !
LGTM 👍

**Comment by ebertin42** [comment]
The problem can occure if your using the "oauth" gem with discordrb. To solve this, use the `RBNACL_LIBSODIUM_GEM_LIB_PATH ` constant to solve the issue.
