### ISSUE TITLE
`VoiceBot#channel` is not updated when bot is moved to different channel

### ISSUE THREAD

**Issue by fizvlad** [discordrb/discordrb#672]
# Summary

`channel` attribute of `VoiceBot` is never changed in runtime, which can cause some errors when bot is working with voice channel it is currently connected to (checking amount of users for instance).

---

## How to reproduce

Simple command bot as an example:

```ruby
# frozen_string_literal: true

# This CommandBot is created to test several interactions with voice connections.

require 'discordrb'

#bot = Discordrb::Commands::CommandBot.new token: 'B0T.T0KEN.here', prefix: '!'
voice_connection = nil

bot.command :join do |event|
  channel = event.author.voice_channel
  if channel
    voice_connection = bot.voice_connect channel
    "Joined channel #{channel.name}"
  else
    "You are not in voice channel!"
  end
end

bot.command :channel do |event|
  if voice_connection
    "Chilling at #{voice_connection.channel.name}"
  else
    "Not in the voice channel"
  end
end

bot.command :leave do |event|
  if voice_connection
    voice_connection.destroy
    "Leaving"
  else
    "I'm not even here"
  end
end

bot.run
```

**Ruby version:**

ruby 2.5.5p157 (2019-03-15 revision 67260) [x64-mingw32]

**Discordrb version:**

master commit: 5f3dcc1a00bae37da1efe9d40f71835a6a18eebd

**Comment by swarley** [comment]
Could you provide clarification on what errors, and or how the data is incorrect? And/or include a sequence that works with your example to replicate the error

**Comment by fizvlad** [comment]
Run the bot at some server with at least two different voice channels, then
1. Join *channel 1*
2. `!join` - bot must join channel
3. `!channel` - bot must reply with name of `VoiceBot#channel` - *channel 1*
4. Move bot to *channel 2* with drag-and-drop
5. `!channel` - bot will again reply with *channel 1* although it is now connected to *channel 2*

**Comment by swarley** [comment]
Thank you, I'll follow up on this in an hour or so

**Comment by z64** [comment]
Handling VSU is the correct approach here.

Note your original script still will not work correctly, since it cannot handle the voice bot being invalidated by a VSU (i.e., right click on bot -> Disconnect).

You should always use `event.voice` or similar for this, and avoid closuring a single VoiceBot instance.
