### ISSUE TITLE
`Bot#stop` need small changes due to #652

### ISSUE THREAD

**Issue by fizvlad** [discordrb/discordrb#675]
# Summary

As mentioned in changelog after #652:
> - **(breaking change)** Removed `no_sync` argument in `Bot#stop` as part of a refactor that removes Ruby 2.3 compatibility ([#652](https://github.com/discordrb/discordrb/pull/652), thanks @PanisSupraOmnia)

However actual `Bot#stop` and its documentation wasn't changed at all.

**Ruby version:**

ruby 2.5.5p157 (2019-03-15 revision 67260) [x64-mingw32]

**Discordrb version:**

master commit 6a230c203f8676add9b01411b51592a9737afd55

**Comment by z64** [comment]
Fixed with #676
