### ISSUE TITLE
ServerDeleteEvent expects full guild object

### ISSUE THREAD

**Issue by fizvlad** [discordrb/discordrb#684]
# Summary

Initialization of unavailable guild can cause `Server#initialize` to raise `#<NoMethodError: undefined method 'map' for nil:NilClass>` at following string:

```ruby
@features = data['features'].map { |element| element.downcase.to_sym }
```

Particulary, you can reproduce this issue by kicking bot from a server. [Guild delete event](https://discordapp.com/developers/docs/topics/gateway#guild-delete) will be raised with [Unavailable Guild Object](https://discordapp.com/developers/docs/resources/guild#unavailable-guild-object) which contain no data fields except for `id`.

*UPD:* This issue can also be reproduced by simply removing server.

---

**Ruby version:**

ruby 2.6.5p114 (2019-10-01 revision 67812) [x64-mingw32]

**Discordrb version:**

master commit 0f74a1e10def06fa82c34a9d517174a496f00657 with `swarley/readpartial_error_handling` branch merged in
*UPD:* Issue is still reproducable at f44dc38a35da2771275cc72a5671adeec463f807

---

**Trace:**

```
[IN : websocket @ 2019-11-27 19:05:06.643] {"t"=>"GUILD_DELETE", "s"=>12, "op"=>0, "d"=>{"id"=>"643061487203778571"}}
Gateway message error!
Exception: #<NoMethodError: undefined method `map' for nil:NilClass>
  /lib/discordrb/data/server.rb:80:in `initialize'
  /lib/discordrb/events/guilds.rb:64:in `new'
  /lib/discordrb/events/guilds.rb:64:in `init_server'
  /lib/discordrb/events/guilds.rb:15:in `initialize'
  /lib/discordrb/bot.rb:1282:in `new'
  /lib/discordrb/bot.rb:1282:in `handle_dispatch'
  /lib/discordrb/bot.rb:694:in `dispatch'
  /lib/discordrb/gateway.rb:725:in `handle_dispatch'
  /lib/discordrb/gateway.rb:690:in `handle_message'
  /lib/discordrb/gateway.rb:628:in `websocket_loop'
  /lib/discordrb/gateway.rb:576:in `connect'
  /lib/discordrb/gateway.rb:470:in `block in connect_loop'
  /lib/discordrb/gateway.rb:469:in `loop'
  /lib/discordrb/gateway.rb:469:in `connect_loop'
  /lib/discordrb/gateway.rb:164:in `block in run_async'
```

**Comment by z64** [comment]
Thanks for the update - also saw the relevant thread in the API docs repo.
`ServerDeleteEvent` will have to be updated to only yield the server ID, since the internal handler will have already removed it from the cache.

**Comment by fizvlad** [comment]
It [turns out](https://github.com/discordapp/discord-api-docs/issues/714) guild ID is only thing which must be expected here.
I suppose it could be solved by changing of behaviour of `Server#initialize` method when `exists` parameter is set to `false` (this event seems to be only place it is used)
