### ISSUE TITLE
Change name on command

### ISSUE THREAD

**Issue by catuss-a** [discordrb/discordrb#690]
Hello guys,

I'm trying to update members names on bot command by doing so:

```ruby
bot.command :set do |event, name|
  Discordrb::API::Server.update_member(bot.token, event.server.id, event.user.id, nick: name)
  return "success"
end
```

But I get a permission error `#<Discordrb::Errors::NoPermission: The bot doesn't have the required permission to do this!>` everytime. The bot is Administrator though and I even tried to only add manage member perm only but still the same.

Any idea ? Or if you know another way to update without providing the token from event it would be nice.

**Comment by swarley** [comment]
Hello! Welcome to discordrb. First of all when using a CommandBot you rarely need to interact with `API` level abstractions. Secondly, this is a tracker for library related issues, and this seems more like a configuration issue. I'd invite you to join our discord server in the ruby_discordrb channel and we can help you further. Thanks!

**Comment by Daniel-Worrall** [comment]
What swarley said, but the bot can only update users equal or below on the role hierarchy. If you are the owner, you won't be able to update it.
As for the abstractions, there's a change_nickname method on the member object you can get from `event.user`

**Comment by catuss-a** [comment]
Ok since I was trying to update myself it makes sense. Thanks for the answer. I tried this method already but then went deep into the code because could not make it work

**Comment by catuss-a** [comment]
Sorry for spamming, I can't post into discord channel since gotta wait 10minutes :P
